### ISSUE TITLE
where to find this data, thanks.

### ISSUE THREAD

**Issue by liamxg** [DidDrog11/LIPS#3]
read_xlsx(here("data", "MRCA_L_segment.xlsx"))

**Comment by DidDrog11** [comment]
Should be available now with the most recent commit https://github.com/DidDrog11/Lassa_phylogeography/commit/b7b5a89bed1628203bd0494d5a73b59d67c18277

Let me know if any other issues.

**Comment by liamxg** [comment]
Thanks, I am very appreciated, I like your research very much, hope you can help me on this, thanks.

**Comment by liamxg** [comment]
mrca_enriched <- mrca_combined %>%
  left_join(., all_sequences, by = c("accession_number" = "accession_lassa")) 


where is "all_sequences"? thanks.

**Comment by DidDrog11** [comment]
The file that is read in at line 28 of https://github.com/DidDrog11/Lassa_phylogeography/blob/master/scripts/3_descriptives.R
