### ISSUE TITLE
where is "nigeria_sf.rds"?

### ISSUE THREAD

**Issue by liamxg** [DidDrog11/LIPS#4]
nigeria_shapefile <- read_rds(here("data", "nigeria_sf.rds"))

**Comment by DidDrog11** [comment]
It is this file (https://github.com/DidDrog11/Lassa_phylogeography/blob/master/data_download/gadm36_NGA_1_sp.rds) saved as an SF object, I will update when I get a moment.

**Comment by liamxg** [comment]
thanks, that's really helpful to me.
