### ISSUE TITLE
where to find API key?

### ISSUE THREAD

**Issue by liamxg** [DidDrog11/LIPS#5]
Error: HTTP failure: 400
{"error":"API key invalid","api-key":"888888","type":"invalid",
"status":"unknown"}

**Comment by DidDrog11** [comment]
You need to generate your own keys for NCBI (https://support.nlm.nih.gov/knowledgebase/article/KA-05317/en-us) and Google (https://developers.google.com/maps/documentation/javascript/get-api-key)

**Comment by liamxg** [comment]
thanks. I will try to do that.
